# Generated by Django 5.1.7 on 2025-03-20 00:04

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AsignationType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Asignation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asignation_date', models.DateField(blank=True, default=django.utils.timezone.now, null=True)),
                ('asignation_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='asignaciones.asignationtype')),
                ('helper', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assisted_asignations', to='asignaciones.person')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='asignaciones.person')),
            ],
        ),
    ]
