# Generated by Django 5.1.7 on 2025-03-20 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asignaciones', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='days_from_last_asignation',
            field=models.IntegerField(default=365),
        ),
        migrations.AddField(
            model_name='person',
            name='visible',
            field=models.BooleanField(default=True),
        ),
    ]
