# Generated by Django 5.1.7 on 2025-04-13 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asignaciones', '0002_person_days_from_last_asignation_person_visible'),
    ]

    operations = [
        migrations.AddField(
            model_name='asignation',
            name='room',
            field=models.IntegerField(choices=[(1, 'Room 1'), (2, 'Room 2')], default=1),
        ),
    ]
