# Generated by Django 5.1.7 on 2025-04-14 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asignaciones', '0003_asignation_room'),
    ]

    operations = [
        migrations.AddField(
            model_name='asignation',
            name='asignation_number',
            field=models.IntegerField(choices=[(3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7')], default=1),
        ),
        migrations.AlterField(
            model_name='asignation',
            name='room',
            field=models.IntegerField(choices=[(1, 'Sala 1'), (2, 'Sala 2')], default=1),
        ),
    ]
