# Generated by Django 5.1.7 on 2025-04-14 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asignaciones', '0004_asignation_asignation_number_alter_asignation_room'),
    ]

    operations = [
        migrations.AddField(
            model_name='asignation',
            name='attended',
            field=models.BooleanField(default=None, null=True),
        ),
    ]
