# Generated by Django 5.1.7 on 2025-04-14 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asignaciones', '0005_asignation_attended'),
    ]

    operations = [
        migrations.AddField(
            model_name='asignation',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
